import React, { Component } from 'react';

import { Page } from './../../Shared/Page.styles';
import BlogPost from '../../Shared/BlogPost/BlogPost';
import { BlogImage } from '../../Shared/BlogPost/BlogPost.styles';
import Header from "../../Shared/Header/Header";

import BansImage from './images/bans.png';
import BanPhase2Image from './images/ban phase 2.png';
import FirstPhaseImage from './images/first phase.png';
import FirstPicksImage from './images/first picks.png';
import LastPicksImage from './images/last picks.png';

class FailuresOfLeagueDraft extends Component {
    render = () => {      
        return (
            <Page>
                <Header currentScroll={1} />
                <BlogPost>                   
                <h2>
					<strong>Failures of the Modern League of Legends Draft<br/></strong>
				</h2>
				<p>It can and should be argued that the draft phase in League of Legends is one of the easiest ways to give your team a definitive advantage prior to the start of the game and can allow a team with mechanically worse players to outperform and beat better teams. By having an advantage from the outset, this should put the onus on the enemy team in order to aggressively try and make up the discrepancy. There are many ways to garner this advantage but it starts with what the goals of the draft should be.</p>
                <p>Goals of A Draft (In Order Of Importance):</p>
                <ul>
                    <li>Create a cohesive theme for the team</li>
                    <li>Have flexible champions that allow for you to counter pick the enemy</li>
                    <li>Have an easier to execute strategy than the opponent</li>
                    <li>Limit or force the enemy to choose off theme champions</li>
                </ul>
                <p>Having an easier to execute strategy generally should mean there is a lower degree of variance in the team composition’s performance, it requires less of an execution requirement, and gives you the ability to limit the amount of information you have to process to make the best decisions. Right now in pro play and for the existence of League as an esport, drafts have focused mostly on just selecting priority or comfort picks that have hints of a similar theme with each other. The problem is that even if a champion is strong in the meta, if they don't fit inside of the theme of the team generally you're just playing a handicapped version of the champion that may not actually be that strong. In some metas, there are picks that are so strong and abusive they should be picked whenever but that also means the theme should cater to the champion even more.</p>
                <p>Let’s take a look at the draft between Immortals and Cloud 9 from Spring Season  on patch 11.5 and try to find the holes in the current drafts and what a possible different route could have been.</p>
                <BlogImage src={BansImage} alt="First Ban Phase" />	
                <p>We haven’t reached the first blue pick (B1) yet and there is already an issue with Immortals ban list here. When we think of blue side bans we need to look at both how red side is selecting their bans, the kinds of champions they want to pick on R1 and R2, and how we should choose a champion for B1. Let’s work our way backwards here to see why the bans from IMT are almost nonsensical. </p>
                <p>For a B1 champion we want a flexible champion that can play multiple lanes and themes as needed. Because it is the first pick of the game choosing a champion that only does one thing well in a single lane leads to an easy and free counter-pick for the opponent. A common B1 pick right now is Hecarim which I generally disagree with since Hecarim has a single mode he can play through right now. It tells me immediately as the opposing team that you want to dive and go in on me aggressively so I should be picking disengage-oriented, mobile champions to completely invalidate Hecarim as a champion. One of the strongest first picks right now is Seraphine who can be flexed to every role but most commonly between mid, support, adc and because of the dominance of Moonstone makes her a power pick in the meta too. I also like champions like Tristana and Lillia for similar reasons.</p>
                <p>Now let’s look at R1 and R2 picks. These follow a thought process mirroring B1 where we want two flexible champions that share a theme but have a flexibility in what that theme is or have flexibility in the lanes they are played while denying power picks for the opponent that synergize with their B1. This means flex champs like Seraphine, Tristana, and Lillia are great here as well as champs like Lulu, Karma, Soraka, Galio, Gragas. Generally on R1 and R2 I don’t like to commit to a specific theme unless I can secure a broken champ or two power picks like Twisted Fate and Gragas.</p>
                <p>With these styles in mind, we can now look at how both sides should ban. As the red side I have the difficult job of managing the power picks, I want all of the strong B1 champions to be eliminated while keeping enough open for myself. Because of this I find Seraphine to probably be a must ban on the red side unless you can secure Lillia/Tristana/Karma for your team. This means most likely the three red side bans should be Seraphine, Lillia, and then Karma if people drafted properly or Tristana.</p>
                <p>For blue side bans, we have a lot more freedom of choice in our bans where we should be focusing on securing our power pick while removing flexible champs that the red side wants. Our first ban can be a more selfish pick and I actually like targeting certain players and playstyles here by banning champs like Gragas that are multiflex or champions like Twisted Fate with the powerful global pressure. However, while our first pick can be greedy we need to be more reactive on our second and third bans. If the red side opts to not ban any power picks we either need to be the ones to limit the field so they can’t secure two or leave them all open and give us the opportunity for 2 or 3 strong champions. It's very possible the blue side needs to ban Lillia/Seraphine/Tristana/Karma on these bans.</p>
                <BlogImage src={FirstPicksImage} alt="First Picks" />
                <p>We can now look at the full bans and B1, R1, and R2 picks and piece apart what went right and wrong. Blue side’s first ban was Olaf which I don’t like. Olaf is a champion that loves moonstone users and has limited themes to him. While he is strong and Blaber is someone you want to limit in the jungle, I’d rather target the other moonstone users that can be flexed if the goal is to not have Blaber pick Olaf. In that case I’d go with Lillia or Seraphine most likely. If we wanted a more selfish ban I could see a Rell ban here too as a powerpick. Cloud9 opts to ban Seraphine first which is an excellent ban. Immortals respond with a Lucian ban. While Lucian is multi-flex, he is easily counterable in both theme and champions and is not blind pickable in many match-ups. Therefore this feels like a waste and could have been done later into the draft phase if need be. Cloud9 then bans Hecarim which signals to me they are going to leave up Lillia and Karma as champions. Because Immortals went with two selfish bans Cloud9 is guaranteed to get at least 2 power picks at a minimum. This is another reason for possibly a Lillia ban on the second blue side ban. Immortals’ last ban is Nautilus which is the worst ban in this phase, it is not a power pick, is not blind pickable, and has a limited theme to him. Immortals ban phase was 3 above average champions that are all counter pickable and all counter pickable by the same themes. Cloud9’s last ban is Udyr as a strong jungler in this patch. This is a more selfish pick but coupled with the Hecarim does mean that the strongest jungler left is Lillia. I think this is a blunder since Lillia is probably the second strongest draft champ in the patch. </p>
                <p>After the ban phase, as Immortals I should be looking to almost insta-lock Lillia to deny one of Cloud9’s best champs, one of the patches strongest champs, and to give me a strong jungler in a limited pool or have the option for jungle counter pick. Instead of this Immortals picks B1 Renekton probably the worst common pick on B1 in the meta right now along with Hecarim, Kaisa, and Gnar. Renekton is a lane bully for top usually but can be flexed mid and is a strong champion but comes with the caveat of you need to win the laning phase. However, he is not a blind pick champion despite his strength, if he loses the laning phase he is useless as a champion. He can be easily countered by many champions and if you try and flex him mid you can easily have your team laneswap to match him or pick two good champs into him. Renekton is a champion that is a trap to look at, he looks insane but that's only when his team is already ahead or he is left unchecked and grows strong on his own. He’s the card game equivalent of a win more card. When you cast it and it works, it feels great and gives you that dopamine hit. But similar to card games you almost never add win more cards to your deck and instead prioritize cards that can proactively earn you that position ahead or allow you to overcome a board state not in your favor. Again Immortals have gone greedy and disrespectful with their picks.</p>
                <p>Cloud9 answers the Renekton first pick with Tristana and Rell, this is an awkward spot to be in with these picks where Lillia is left open for Immortals but would likely be forced into the jungle. The Rell pick on R2 while not usually my favorite does deny it from Immortals as a strong, aggressive dive champion that wants to go in with Renekton. However, it is open to Immortals hard countering it in bot lane. Tristana is an excellent choice here as she can out-range Renekton in team fights and will likely force Immortals to have a worse bot lane since Cloud9 has the option for a counterpick. </p>
                <p>As of this moment, I would say Cloud9 is ahead in the draft. We can now move on to the rest of phase 1 of the draft.</p>
                <BlogImage src={FirstPhaseImage} alt="First Phase" />
                <p>Something very wrong happened here for Immortals. Their next two picks are Thresh and Syndra. While Thresh is sometimes a counter to Rell, Karma is a bigger counter, gives you moonstone synergies and can be placed mid or support. The Syndra pick makes no sense at this time. While all three of Immortals’ champs are aggressive champions that want to go in and fight which is good, each of these three champions are now set to be countered by Cloud9 going into the second ban phase.</p>
                <p>Cloud9 just instantly locks in Lillia to secure another power pick for them and their moonstone user which synergizes incredibly well with Tristana and Rell. Cloud9 is heavily winning the draft phase still.</p>
                <p>Going into the second ban phase as Immortals I want to take on my own moonstone user as well as forcing Cloud9 into continuing down the team fight side of things. There is also the option of sending Syndra bot as the adc and taking someone like a Karma mid or top. If we don’t have that flexibility to have a mage bot we’ll need to prioritize our bans for mid or top to give Renekton a good or even matchup. I’d probably ban Gangplank here 100% as he synergizes well with moonstone, beats Renekton, has a global ultimate, and can be both an aggressive team fighter or a disengage presence with his terrain control. As Cloud9, I’m probably looking at sending Tristana bot lane and picking a strong counter to Renekton and Syndra. We can opt in to the team fight comp and try to win teamfights via better lanes. We can also go for a poke or disengage comp still with the winning match up top. Because of this I probably want to shorten the jungle pool even more with both bans and if they choose a matchup that is bad for us we can easily pivot on R5 to have Tristana top or middle as needed.</p>
                <BlogImage src={BanPhase2Image} alt="Second Ban Phase" />
                <p>Both of Immortals’ picks are aimed at the top lane here to give Renekton the edge he needs, however both bans don’t make much sense. Gnar is a laner that goes even with Renekton and is more of a skill matchup along with relying on top-jungle synergy. Gnar is also a champion similar to Renekton where unless his team is ahead Gnar is pretty useless. Meanwhile the Gragas ban is slightly strange where it loses the lane to Renekton but does offer the disengage utility to the team that counters Renekton and could harm the rest of the composition. It also benefits from Moonstone. At a minimum I’d swap the Gnar ban for a Gangplank ban. Both of Cloud9’s picks follow what was expected too; both champions are ones that Xerxe has played and will force him on a lower tier jungler with 8 possible jungle champions banned or taken already. In particular while I don’t think Nidalee is that good of a champion her Moonstone synergy takes away another one of Immortals outs for having an even team composition.</p>
                <p>If I’m Cloud9 I either pick Gangplank on B4 leaving the final counter-pick for mid on R5 or we can still retain the flex for top and pick a mid with the assumption of going up against Syndra. I personally like Karma here as my number one pick and can still retain flex. Azir or Viktor is also good in this match up. My final recommendation would be R4 Karma and R5 Gangplank.</p>
                <p>For Immortals I want to try and secure the Karma for mid and have a Thresh and Syndra bot lane. Syndra has a winning match-up into Tristana and Karma synergizes very well here. We’d need a jungler that could get benefit from moonstone and is good in team fights. This is a probable Skarner, Taliyah, or Nocturne, something that can go top and get Renekton ahead with some sort of AP ratios to make itemization against Renekton harder to do and go with Karma. In the event Cloud9 take Karma, you could try Soraka with the same idea and the added silence to make the hard engage of Immortals better or keep Syndra mid and go for more of a poke composition with a Caitlyn, Varus, or Ezreal bot lane. Jinx would also work but would probably require a tankier jungler. For junglers I’d probably have to recommend the same 3 as the other composition but could see a Karthus potentially working here too.</p>
                <BlogImage src={LastPicksImage} alt="Last Picks" />
                <p>This is Cloud9’s first major blunder. The Sion goes even into Renekton and while the kill pressure is nice with Lillia this champion isn’t as synergistic as I want. This pushes Cloud9 more towards the team fight composition.</p>
                <p>In response, Renekton is feeling a lot safer so we can go more aggressive junglers here. In an ideal world we just send Syndra wherever Tristana goes with the expectation of bot lane here.  I would take Karma/Nocturne and go for the immediate gank top after clearing the jungle or just go Ezreal/Nocturne. Immortals does opt into the Nocturne but goes Draven here which does have kill pressure on bot lane but if you want the winning lane Caitlyn is just better I feel. However, Draven is a hyper carry so if he gets fed he can roll through Cloud9. Essentially we have two sinful, greedy champions that must win lane now.</p>
                <p>The last pick for Cloud9 is Orianna. Orianna is an incredibly safe champion that goes even into the Syndra this does make Cloud9’s composition more team fight oriented and has synergy with the moonstone on Lillia. You could still opt into Karma or Soraka as the last pick for Cloud9 both in the midlane but the protection aspect of Orianna is nice and could allow you to take on Immortals in a team fight as long as Draven or Renekton doesn’t get ahead.</p>
                <p>Overall Cloud9’s team composition is favored over Immortals, top and mid lane are even, bottom is Immortals favored, and jungle is Cloud9 favored but the overall theme and playstyle of Cloud9’s composition is easier to execute. If Cloud9 goes even after laning phase and can secure a dragon or two they are poised to win as they can hang back and let their team scale up. The healing from moonstone will be huge in prolonging the team fights to allow Cloud9 to win. Immortals have to take the initiative and have aggressive ganks top and bot to get the two carries ahead. Unfortunately armor is very good and easier for Cloud9 to itemize for compared to Immortals that will have a tougher time itemizing.</p>
                </BlogPost>
            </Page>
        );
    }
}

export default FailuresOfLeagueDraft;